# Generated by Django 3.1 on 2020-09-11 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BangladeshUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dailytotaltest', models.IntegerField(null=True)),
                ('dailypositive', models.IntegerField(null=True)),
                ('dailyrecoverd', models.IntegerField(null=True)),
                ('dailydeath', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(blank=True, default='not added', max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(blank=True, default='not added', max_length=200, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('noOftest', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorldUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dailytotaltest', models.IntegerField(null=True)),
                ('dailypositive', models.IntegerField(null=True)),
                ('dailyrecoverd', models.IntegerField(null=True)),
                ('dailydeath', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('status', models.CharField(blank=True, choices=[('pending', 'pending'), ('positive', 'positive'), ('negative', 'negative')], default='pending', max_length=100, null=True)),
                ('testcenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coronalab.testcenter')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coronalab.reguser')),
            ],
        ),
    ]
