# Generated by Django 3.1 on 2020-09-12 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coronalab', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reguser',
            name='password',
        ),
    ]
